language: python

matrix:
    include:
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36

sudo: false
install:
  - travis_retry pip install tox
  - if [[ $TOXENV == 'py27' ]]; then pip install -r requirements-dev.txt; pip install -e .; fi
script:
  - tox
  # We only need to run the lint/flake8 checks on one version of python
  # So I've arbitrarily chosen python2.7.
  - if [[ $TOXENV == 'py27' ]]; then make check; fi
